apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gorph

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

labels:
- includeSelectors: true
  pairs:
    app: gorph
    version: v1.0.0 